apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-annotation
  labels:
    environment: dev
  annotations:
    description: this container is mean for testing purpose only, any use of misleading will not be tolerated
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80